In [8]:
import numpy as np
import sys
import os

from dplearning.book_material.common.util import im2col

sys.path.append('book_material')
from common.util import *

In [9]:
x1=np.random.rand(1,3,7,7)

In [10]:
col1=im2col(x1,3,3,stride=1,pad=0)

In [11]:
col1.shape

(25, 27)

In [ ]:
class Convolution(object):
    def __init__(self,W,b,stride=1,pad=0):
        self.W=W
        self.b=b
        self.stride=stride
        self.pad=pad
    def forward(self,x):
        ###输入数据形状
        N,C,H,W=x.shape
        ###卷积核原始形状
        FN,C,FH,FW=self.W.shape
        ###im2col 得到一个N*OH*OW * FH*FW*C的矩阵
        x_col=im2col(x,FH,FW,stride=self.stride,pad=self.pad)
        ###先计算输出的特征图宽和高
        out_h=1+(H+2*self.pad-FH)/self.stride
        out_w=1+(W+2*self.pad-FW)/self.stride
        ###权重矩阵reshape为 FH*FW*C * FN的形状由于FN是最外层维度 所以要先FN * XXX 然后转置
        w_col=self.W.reshape(FN,-1).T
        #### 计算 得到结果应该是 N*OH*OW *  FN 的结果
        out=np.dot(x_col,w_col)+self.b
        ###其中N是分组不用动但是FN实际上是通道 所以要transpose回来
        out.reshape(N,out_h,out_w,-1).transpose(0,3,1,2)
        return out

In [26]:
class pooling:
    def __init__(self,pool_h,pool_w,stride=1,pad=0):
        self.pool_h=pool_h
        self.pool_w=pool_w
        self.stride=stride
        self.pad=pad
    def forward(self,x):
        N,C,H,W=x.shape
        out_h=1+(H+2*self.pad-H)/self.stride
        out_w=1+(W+2*self.pad-W)/self.stride
        x_col=im2col(x,self.pool_h,self.pool_w,stride=self.stride,pad=self.pad)
        x_col=x_col.reshape(-1,self.pool_h*self.pool_w)
        out=np.max(x_col,axis=1)
        out=out.reshape(N,out_h,out_w,-1).transpose(0,3,1,2)
        return out

In [27]:
print(test)

[[[[0.98773548 0.69000007]
   [0.40095929 0.97136407]]

  [[0.39045916 0.39684771]
   [0.09744227 0.17336547]]]


 [[[0.9375689  0.82249621]
   [0.85851668 0.95539596]]

  [[0.20194441 0.1100764 ]
   [0.28920022 0.96031423]]]]


In [30]:
print(test.reshape(2,-1))

[[0.98773548 0.69000007 0.40095929 0.97136407 0.39045916 0.39684771
  0.09744227 0.17336547]
 [0.9375689  0.82249621 0.85851668 0.95539596 0.20194441 0.1100764
  0.28920022 0.96031423]]


In [25]:
test.reshape(-1,4)

array([[0.89114876, 0.97023993, 0.4118958 , 0.02695672],
       [0.61754829, 0.45322836, 0.80104408, 0.99073972],
       [0.77416761, 0.17963067, 0.89798723, 0.50999748]])

In [37]:
test1=np.random.rand(2,2,3)

In [39]:
print(test1)

[[[0.10796304 0.74878484 0.73659782]
  [0.20645317 0.99819547 0.6891635 ]]

 [[0.95957394 0.11388469 0.95975274]
  [0.23919791 0.7766131  0.87194025]]]


In [41]:
print(test1.reshape(2,-1))

[[0.10796304 0.74878484 0.73659782 0.20645317 0.99819547 0.6891635 ]
 [0.95957394 0.11388469 0.95975274 0.23919791 0.7766131  0.87194025]]
