In [3]:
import torch
devices=torch.device('cpu')
##sparse系列函数
# sparse 系列函数用于处理稀疏张量（Sparse Tensor），它们专门针对数据中大部分元素为零的高效存储和计算场景设计。
# #sparse_coo_tensor 是其中一种构造稀疏张量的方法，代表 COO（Coordinate）格式的稀疏张量。
# 稀疏张量通过仅存储非零元素的坐标和值，避免存储大量零值，从而显著节省内存和计算资源。

In [4]:
# out (Optional[Tensor], 可选)
# 指定输出张量。若提供，结果会直接写入此张量，需确保其形状和数据类型兼容。
#
# dtype (Optional[dtype], 可选)
# 指定输出张量的数据类型（如 torch.float32, torch.int64）。若未提供，则根据输入数值推断。
#
# device (Optional[DeviceLikeType], 可选)
# 指定张量存储的设备（如 "cpu", "cuda:0"）。默认使用当前设备。
#
# requires_grad (bool, 默认=False)
# 是否为此张量启用自动求导。用于构建计算图，常用于模型训练。
#
# pin_memory (bool, 默认=False)
# 是否将张量锁定在页锁内存（Pinned Memory），可加速数据从CPU到GPU的传输。
x=torch.arange(10,device=torch.device(devices))

In [5]:
# out (Tensor, optional) – the output tensor.
# dtype (torch.dtype, optional) –指定张量类型
# layout (torch.layout, optional) – 指定张量布局 默认是torch.stride 还有sparse 也就是稀疏矩阵的布局
# device (torch.device, optional) – 设备
# requires_grad (bool, optional) – If autograd should record operations on the returned tensor. Default: False.
torch.zeros(2) ##主要参数可以是可变数量参数也可是数组元素等形式
torch.ones(2)
#*_like() 系列函数（如 torch.rand_like()）: 根据输入张量的形状和数据类型生成新张量

tensor([1., 1.])

In [6]:
torch.arange(1,9)##range已经废除了

tensor([1, 2, 3, 4, 5, 6, 7, 8])

In [7]:
###通常的+-*/ 求幂 都是按元素运算结果

In [8]:
###张量连接

In [9]:
x=torch.arange(6,dtype=torch.float32).reshape(2,3)
y=torch.tensor([[1,2],[2,3]])
torch.cat([x,y],axis=1) ##连接的维度必须要相等比如2*3 和 2*5 可以按行拼接

tensor([[0., 1., 2., 1., 2.],
        [3., 4., 5., 2., 3.]])

In [10]:
###逻辑运算符构建二元张量 两个张量格式必须完全一致
a=torch.randn([1,2])
b=torch.randn([1,2])
result=(a==b)
###张量求和
result.sum()
##或者
torch.sum(result)

tensor(0)

In [11]:
###广播机制 与numpy类似
# 当两个张量格式不一样时
# 通过适当复制元素来扩展一个或两个数组，以便在转换之后，两个张量具有相同的形状；
# 对生成的数组执行按元素操作。
x=torch.randn([3,1])
y=torch.randn([1,3])

In [12]:
##索引与切片与numpy和list类似

In [13]:
## list x = y 是变量重新绑定操作，而 x[:] = y 是原地修改操作， torch.tensor也有类似的操作
Z = torch.zeros([1,2])
print('id(Z):', id(Z))
Z[:] = torch.zeros([2])
print('id(Z):', id(Z))

id(Z): 2152778326352
id(Z): 2152778326352


In [14]:
###转换为其他python对象
x=torch.tensor([2,3])
x.numpy()
one_num=torch.tensor([1])
one_num.item()###只有一个元素的张量才可以使用item （）函数

1

In [15]:
x=torch.tensor([2,3])