In [1]:
import torch

In [6]:
x=torch.ones([2,3,3])

降维聚合

In [15]:
x.sum(axis=0) ##聚合函数 axis取值结果技巧，axis取的几 则这个轴就会清除掉
##均值两种求法
x.mean()==x.sum()/x.numel()

tensor(True)

In [16]:
##均值两种求法
x.mean(axis=0)==x.sum(axis=0)/x.shape[0]

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

非降维计算

In [51]:
x=torch.ones([2,3,3])
x.sum(axis=1,keepdims=True)
x.mean(axis=1,keepdim=True)
##注意不可以这样x.mean(keepdim=True) 必须要指定轴 比如下面这样 
#神奇
x.mean(axis=[0,1,2],keepdim=True)

tensor([[[1.]]])

点积——针对两个向量的,要求向量长度必须相等

In [31]:
x=torch.ones([4])
y=torch.ones([4])

In [32]:
torch.dot(x,y)==torch.sum(x*y)

tensor(True)

矩阵——向量积 针对矩阵与向量的的 要求必须为n*m 与一个向量的乘积

In [41]:
x=torch.ones([2,3])
y=torch.ones([3])
##两行三列 与三行一列 把y从 3个元素转为了2个元素

In [43]:
torch.mv(x,y)

tensor([3., 3.])

矩阵—矩阵乘法  两个矩阵mn 和np的乘法

In [44]:
x=torch.ones([2,3])
y=torch.ones([3,2])

In [47]:
torch.mm(x,y)==x@y

tensor([[True, True],
        [True, True]])

范数（norm）。
非正式地说，向量的范数是表示一个向量有多大。 这里考虑的大小（size）概念不涉及维度，而是分量的大小。

In [56]:
x=torch.ones([2,3])
##dim为按照那个轴进行计算，p则为范数类型
torch.norm(x,dim=0,p=3)

tensor([1.2599, 1.2599, 1.2599])