In [3]:
%matplotlib inline
import torch
from torch.distributions import multinomial
from d2l import torch as d2l

In [34]:
fair_probs = torch.ones([6])/6 ###6个面 每个面的概率为多少
multinomial.Multinomial(1, fair_probs).sample() ##定义一个多项分布，抽样一次

tensor([0., 0., 0., 1., 0., 0.])

In [23]:
multinomial.Multinomial(10, fair_probs).sample() ##定义十次多项分布

tensor([1., 2., 2., 3., 2., 0.])

In [35]:
# 将结果存储为32位浮点数以进行除法
counts = multinomial.Multinomial(1000, fair_probs).sample()
counts / 1000  # 相对频率作为估计值

tensor([0.1710, 0.1580, 0.1750, 0.1630, 0.1570, 0.1760])