In [2]:
import torch
import torchvision
from torch import nn

torch.device('cpu'), torch.device('cuda'),torch.device('cuda:1')

(device(type='cpu'), device(type='cuda'), device(type='cuda', index=1))

In [3]:
torch.device('cuda:1')

device(type='cuda', index=1)

# 查看有多少gpu可用

In [4]:
torch.cuda.device_count()

1

In [5]:
def try_gpu(i=0):
    if torch.cuda.device_count() >=i+1:
        return torch.device(f'cuda:{i}')
    return torch.device(f'cpu')
def try_all_cpu():
    if torch.cuda.is_available():
        device=[torch.device(f'cuda:{i}') for i in range(torch.cuda.device_count())]
        return device
    else:
        return [torch.device('cpu')]

张量与cpu

In [6]:
x=torch.tensor([1,2,3])
##查询张量所在设备
x.device

device(type='cpu')

In [7]:
y=torch.tensor([4,5,6],device=try_gpu())

In [8]:
y.device

device(type='cuda', index=0)

张量复制

两个张量不在一个设备上的时候无法进行运算

In [12]:
x.cuda(0)##这样不会把x移动到其他设备上 必须要赋值给别的变量
z=x.cuda(0)## 这种方式可以把x挪到cuda1上 但是用z接受

假设变量Z已经存在于第二个GPU上。 如果我们还是调用Z.cuda(1)会发生什么？ 它将返回Z，而不会复制并分配新内存。

In [17]:
x.to(torch.device('cuda'))

tensor([1, 2, 3], device='cuda:0')

In [18]:
x

tensor([1, 2, 3])

In [14]:
z.cuda(0) is z ##结果为真，说明这样并不会重新分配地址a

True

神经网络与gpu

In [15]:
net = nn.Sequential(nn.Linear(3, 1))

In [16]:
net.cuda(0)

Sequential(
  (0): Linear(in_features=3, out_features=1, bias=True)
)

In [37]:
net[0].bias

Parameter containing:
tensor([-0.5196], device='cuda:0', requires_grad=True)

In [38]:
net.state_dict()

OrderedDict([('0.weight',
              tensor([[ 0.3944, -0.5263, -0.4638]], device='cuda:0')),
             ('0.bias', tensor([-0.5196], device='cuda:0'))])