In [5]:
import pandas as pd

In [2]:
s.add('a')

In [3]:
s

{'a'}

In [1]:
import torch

In [2]:
x=torch.randn(2,3)

In [10]:
x=x.to(dtype=torch.int)

In [7]:
torch.embedding(padding_idx=)

tensor([[ 0.5322,  1.7238, -0.3872],
        [ 0.3376, -1.2144, -0.2541]])

In [15]:
import pandas as pd

In [18]:
df=pd.DataFrame({'a':[1,2,3]})

In [30]:
a=

In [35]:
import numpy as np

a,b,c=np.array(df)

In [36]:
a

array([1], dtype=int64)

In [1]:
import torch

In [2]:
torch.cat([torch.randn(2,3),torch.randn(2,3)],dim=-1)

tensor([[ 0.1262,  1.4129,  1.7383,  0.8452,  0.2662, -1.1897],
        [ 0.2942,  0.3428,  0.9440,  0.6626, -0.5189, -0.0476]])

In [24]:
df=pd.DataFrame({'a':[1,2,3]})

In [25]:
d=df.copy(deep=True)

In [26]:
id(d)

2811900967824

In [27]:
id(df)

2811900968528

In [28]:
import torch

In [38]:
x=torch.tensor([1000000,2,3],dtype=torch.int32)

In [39]:
x

tensor([1000000,       2,       3], dtype=torch.int32)

In [40]:
pip install torchtext


   ---------------------------------------- 0.0/1.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.9 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.9 MB ? eta -:--:--
   --------------------- ------------------ 1.0/1.9 MB 4.2 MB/s eta 0:00:01
   --------------------- ------------------ 1.0/1.9 MB 4.2 MB/s eta 0:00:01
   --------------------- ------------------ 1.0/1.9 MB 4.2 MB/s eta 0:00:01
   ---------------------------------------- 1.9/1.9 MB 2.0 MB/s eta 0:00:00



[notice] A new release of pip is available: 24.3.1 -> 25.1.1
[notice] To update, run: D:\work softwar\python\python.exe -m pip install --upgrade pip


In [1]:
import torchtext

OSError: [WinError 127] 找不到指定的程序。