In [24]:
import numpy as np
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms, datasets

In [33]:
trans_compose=transforms.Compose([transforms.Resize((128,128)),transforms.ToTensor()])
test_data=datasets.CIFAR10(root='../data', train=False, download=True, transform=trans_compose)

In [34]:
##test_loader是DataLoader的结果会把 datasets中的target 和 data按照batch_size的大小打包 并且可选是否随机
##不可以用索引访问因为没有实现__getitem__方法但是实现了 __iter__方法因为shuffle=True的时候每次迭代结果不同
###test_loader.dataset 实际上访问的是加载进来的底层源数据集
# DataLoader 内部生成一个随机排列的索引序列（例如 [3, 1, 0, 2]）。
# 按这个索引序列从 Dataset 中提取数据，但不会修改 Dataset 的原始数据存储顺序。
# test_loader.dataset 直接指向原始的 Dataset 对象，因此其数据顺序始终不变。
test_loader = DataLoader(test_data, batch_size=4, shuffle=True,num_workers=0,drop_last=False)

In [50]:
for data in test_loader:
    img,target = data
    print(img.shape)
    print(target)

torch.Size([4, 3, 128, 128])
tensor([9, 6, 5, 9])
torch.Size([4, 3, 128, 128])
tensor([1, 7, 8, 5])
torch.Size([4, 3, 128, 128])
tensor([0, 7, 4, 6])
torch.Size([4, 3, 128, 128])
tensor([9, 5, 8, 8])
torch.Size([4, 3, 128, 128])
tensor([5, 2, 9, 6])
torch.Size([4, 3, 128, 128])
tensor([9, 9, 6, 6])
torch.Size([4, 3, 128, 128])
tensor([6, 9, 3, 8])
torch.Size([4, 3, 128, 128])
tensor([4, 3, 6, 4])
torch.Size([4, 3, 128, 128])
tensor([4, 3, 0, 0])
torch.Size([4, 3, 128, 128])
tensor([8, 6, 2, 3])
torch.Size([4, 3, 128, 128])
tensor([5, 2, 2, 1])
torch.Size([4, 3, 128, 128])
tensor([5, 1, 7, 6])
torch.Size([4, 3, 128, 128])
tensor([6, 3, 3, 7])
torch.Size([4, 3, 128, 128])
tensor([0, 5, 0, 0])
torch.Size([4, 3, 128, 128])
tensor([1, 8, 1, 3])
torch.Size([4, 3, 128, 128])
tensor([1, 4, 5, 3])
torch.Size([4, 3, 128, 128])
tensor([3, 9, 6, 3])
torch.Size([4, 3, 128, 128])
tensor([4, 2, 4, 5])
torch.Size([4, 3, 128, 128])
tensor([0, 4, 8, 1])
torch.Size([4, 3, 128, 128])
tensor([3, 2, 4, 8])


KeyboardInterrupt: 

In [40]:
for i in test_loader:
    img,target=i
    print(img.shape,target)

torch.Size([4, 3, 128, 128]) tensor([3, 2, 4, 2])
torch.Size([4, 3, 128, 128]) tensor([3, 0, 5, 6])
torch.Size([4, 3, 128, 128]) tensor([2, 2, 7, 0])
torch.Size([4, 3, 128, 128]) tensor([2, 7, 8, 6])
torch.Size([4, 3, 128, 128]) tensor([4, 2, 9, 5])
torch.Size([4, 3, 128, 128]) tensor([9, 1, 3, 8])
torch.Size([4, 3, 128, 128]) tensor([2, 8, 4, 0])
torch.Size([4, 3, 128, 128]) tensor([2, 1, 5, 3])
torch.Size([4, 3, 128, 128]) tensor([2, 6, 9, 7])
torch.Size([4, 3, 128, 128]) tensor([4, 7, 3, 8])
torch.Size([4, 3, 128, 128]) tensor([1, 3, 0, 9])
torch.Size([4, 3, 128, 128]) tensor([6, 9, 4, 5])
torch.Size([4, 3, 128, 128]) tensor([3, 6, 3, 5])
torch.Size([4, 3, 128, 128]) tensor([3, 8, 8, 9])
torch.Size([4, 3, 128, 128]) tensor([3, 9, 5, 7])
torch.Size([4, 3, 128, 128]) tensor([3, 3, 0, 2])
torch.Size([4, 3, 128, 128]) tensor([7, 0, 1, 6])
torch.Size([4, 3, 128, 128]) tensor([6, 7, 7, 9])
torch.Size([4, 3, 128, 128]) tensor([3, 1, 6, 9])
torch.Size([4, 3, 128, 128]) tensor([4, 1, 4, 2])


In [27]:
test_loader.dataset.shape

AttributeError: 'CIFAR10' object has no attribute 'shape'

In [25]:
Image.open()

C:\Users\Zzz\AppData\Local\Temp\ipykernel_5248\2331312682.py:1: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments.
  Image.open(np.array(img))


AttributeError: 'numpy.ndarray' object has no attribute 'read'